### Lab 4 Exercise 2

Exercise 1: Lists and Arrays 

Task: Create a list and an array, perform some basic operations, and print the results (list 1 contains numbers 1 to 5 and list 2 contains numbers from 6 to 10) 

In [5]:
import numpy as np
import pandas as pd

a = np.arange(1,6)
b = np.arange(6,11)
a,b
print("added array:", (a+b))

added array: [ 7  9 11 13 15]


Exercise 2: Loading Data from Files 

Task: Load data from a CSV file and print the first few rows. 

In [4]:
import csv

file = open("sample_data1.csv","r")
tmplist =[]
for row in file: 
    tmplist.append(row)
file.close()

for i in range(0,6):
    print(tmplist[i])

id,name,age,height,weight,income

1,Alice,29,165,55,50000

2,Bob,32,175,85,60000

3,Charlie,,180,90,70000

4,David,45,165,80,75000

5,Eva,37,160,70,85000



In [6]:
data =pd.read_csv('sample_data1.csv')
print(data.head())

   id     name   age  height  weight   income
0   1    Alice  29.0   165.0    55.0  50000.0
1   2      Bob  32.0   175.0    85.0  60000.0
2   3  Charlie   NaN   180.0    90.0  70000.0
3   4    David  45.0   165.0    80.0  75000.0
4   5      Eva  37.0   160.0    70.0  85000.0


 

Exercise 3: Numpy and Array Indexing 

Task: Create a numpy array and perform indexing and slicing operations. 

In [9]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array[1][2])
print(array[0:2,1:2])
print(array[:2,1:])

6
[[2]
 [5]]
[[2 3]
 [5 6]]


Exercise 4: Creating and Indexing Numpy Arrays 

Task 1: Create a 1D Numpy Array and Access Elements 

Create a 1D numpy array with values from 0 to 9. 

Access the 5th element of the array. 

Access the last element of the array. 

In [12]:
b = np.arange(0,10)
print(b)
print("The fifth element:", b[4])
print("The last element:", b[-1])

[0 1 2 3 4 5 6 7 8 9]
The fifth element: 4
The last element: 9


Task 2: Create a 2D Numpy Array and Access Elements 

Create a 2D numpy array with shape (3, 3) containing values from 1 to 9. 

Access the element at the 2nd row and 3rd column. 

Access the first row. 

Access the first column. 

In [18]:
c = np.arange(1,10).reshape(3,3)
print(c)
print("The 2nd row and 3rd columm:", c[1][2])
print("The first row:", c[0])
print("The first column:",c[:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The 2nd row and 3rd columm: 6
The first row: [1 2 3]
The first column: [1 4 7]


Exercise 2: Slicing and Advanced Indexing 

Task 1: Slice a 1D Numpy Array 

Create a 1D numpy array with values from 10 to 19. 

Slice the array to get elements from index 3 to 7. 

Slice the array to get every second element. 

In [21]:
d = np.arange(10,20)
print(d)
print("Slicing from index 3 to 7:", d[3:8])
print("Slicing to get every second element:",d[::2])

[10 11 12 13 14 15 16 17 18 19]
Slicing from index 3 to 7: [13 14 15 16 17]
Slicing to get every second element: [10 12 14 16 18]


Task 2: Slice a 2D Numpy Array 

Create a 2D numpy array with shape (4, 4) containing values from 1 to 16. 

Slice the array to get the sub-array from rows 1 to 2 and columns 2 to 3. 

Slice the array to get the last two rows. 

Slice the array to get the first two columns. 

 

In [24]:
e = np.arange(1,17).reshape(4,4)
print(e)
print("Slice the array to get the sub-array from rows 1 to 2 and columns 2 to 3",e[1:3,2:4])
print("Slice the array to get the last two rows",e[-2:,:])
print("Slice the array to get the first two columns",e[:,:2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Slice the array to get the sub-array from rows 1 to 2 and columns 2 to 3 [[ 7  8]
 [11 12]]
Slice the array to get the last two rows [[ 9 10 11 12]
 [13 14 15 16]]
Slice the array to get the first two columns [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


Exercise 3: Boolean Indexing and Fancy Indexing 

Task 1: Boolean Indexing 

Create a 1D numpy array with values from 0 to 9. 

Use boolean indexing to get elements greater than 5. 

Use boolean indexing to get elements that are even. 

 



 

In [26]:
f= np.arange(0,10)
mask = f>5
print(f)
print("get elements greater than 5:", f[mask])
mask = f%2==0
print("get elements greater than are even:", f[mask])


[0 1 2 3 4 5 6 7 8 9]
get elements greater than 5: [6 7 8 9]
get elements greater than are even: [0 2 4 6 8]


Task 2: Fancy Indexing 

Create a 2D numpy array with shape (4, 4) containing values from 1 to 16. 

Use fancy indexing to get the elements at positions (0, 0), (1, 2), (2, 3), and (3, 1). 

In [28]:
g = np.arange(1,17).reshape(4,4)
print(g)
print("at(0, 0):",g[0][0])
print("at(1, 2):",g[1][2]) 
print("at(2, 3):" ,g[2][3]) 
print("at (3, 1):",g[3][1]) 

fancy_indexed_elements = g[[0,1,2,3],[0,2,3,1]]
print("Elements at (0, 0), (1, 2), (2, 3), and (3, 1):",fancy_indexed_elements)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
at(0, 0): 1
at(1, 2): 7
at(2, 3): 12
at (3, 1): 14
Elements at (0, 0), (1, 2), (2, 3), and (3, 1): [ 1  7 12 14]
